Imputation manual construction
ONSdigital/statistical-methods-library pull request #186
Opened 2024-05-09 16:40 UTC by vidhyamanisankar

## Synopsis

Briefly describe the purpose of the pr.

## Checklist

- [ ] Documentation created/updated
- [ ] Tests created/updated

## Description

Add a more detailed description of the pr if necessary (can reference release
notes if included).

2024-05-09 17:04 UTC, mwirikia commented on statistical_methods_library/imputation/engine.py
> +    # input_df.show(100)
is this for some future need?

2024-05-09 17:04 UTC, mwirikia commented on statistical_methods_library/imputation/engine.py
> +    # input_df.show(100)
this too?

2024-05-14 10:43 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +    # input_df.show(100)
It is a draft pr & I will refactor once it is 'ready for review'

2024-05-14 10:43 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +    # input_df.show(100)
It is a draft pr & I will refactor once it is 'ready for review'

2024-05-20 08:07 UTC, mwirikia commented on tests/imputation/mean_of_ratios.toml
> +#TODO check
does this mean there is more to do? Or future task not for this ticket?

2024-05-20 08:36 UTC, vidhyamanisankar commented on tests/imputation/mean_of_ratios.toml
> +#TODO check
It was missed while refactoring.

2024-05-20 12:50 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +        apply_manual_construction = True
updated so now existing  method `validate_dataframe` in utilities will throw missing column error when column is not in dataframe.

2024-05-21 15:25 UTC, BenLatham requested changes

2024-05-21 15:43 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +        )
This to cover the scenario when the results run for multiple periods ie. start & end period is different  , so it is possible to have FIMC in the period window. FIMC should n't be included in link calculation as it isn't cleaned response  that why we are filtering out FIMC .

2024-05-21 15:44 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +        )
It implemented as expected

2024-05-21 15:44 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +                    == Marker.FORWARD_IMPUTE_FROM_MANUAL_CONSTRUCTION.value
same as prev. comment

2024-05-21 16:09 UTC, BenLatham commented on statistical_methods_library/imputation/engine.py
>          prepared_df = prepared_df.unionByName(
I missed the filter on l357, that prevents addition of the MCs FIMC

2024-05-21 16:46 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +        )
yes FIMC is not needed here so removed

2024-05-21 17:32 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +        manual_construction_data = (
To fill the links, counts data in ms dataframe, it must be joined back to prepare dataframe So join is inevitable. Applying the {dropDuplicates} transformation prior to joining will fix the duplicate rows created during the join, it will eliminate the performance concern. Since ratio_calculator does multiple complex calculations so it is cleaner to do the mc df joining outside the ratio calculator. In addition ratio calculator, fillna & join transformation are called inside python for loop. I would rather do it in pyspark style. To resolve review comments, `dropDuplicates`  been added.

2024-05-21 17:33 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +                    == Marker.FORWARD_IMPUTE_FROM_MANUAL_CONSTRUCTION.value
been removed

2024-05-21 18:32 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +        if df.filter(col("output").isNull()).count() == 0 and stage == construct_values:
output is null in df after FIR when contributor not respond and the previous period was MC. Without the `stage` clause in if condition applies the break which stops BI,FIMC,C,FIC imputation happening.  I slightly modify  the if to keep the same behaviour when manual_construction_col is none however we have keep stage for MC scenario. Is it ok now?

2024-05-22 16:50 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +        if df.filter(col("output").isNull()).count() == 0 and stage == construct_values:
updated if condition However we are unable to fully remove the `stage == construct_value` clause as it is hi-lighting the existing issue - back data been added up with modified marker/output value in the output which is not expected behaviour.

2024-05-22 16:52 UTC, vidhyamanisankar commented on statistical_methods_library/imputation/engine.py
> +        manual_construction_data = (
As we discussed , Select columns & fillna have been done in dynamic way.

2024-05-23 10:02 UTC, BenLatham approved these changes

2024-05-23 10:41 UTC, BenLatham approved these changes

2024-05-23 16:30 UTC, BenLatham approved these changes

2024-05-23 16:36 UTC, merged